apiVersion: otto.gptscript.ai/v1
kind: Workflow
metadata:
  name: w1wf
  namespace: default
spec:
  manifest:
    prompt: You are a friendly assistant
    output: The final number and the chose fruit
    workflows:
      - subflow
    steps:
      - step: Pick a number
      - step: Now add 1 to it
      - step: Now multiply by two
      - if:
          condition: The number is less than 100
          steps:
          - step: Subtract 2
          - while:
              maxLoops: 4
              condition: Number is less than 100
              steps:
              - step: Multiply times two
          - step: now invoke the workflow called subflow



---
apiVersion: otto.gptscript.ai/v1
kind: Workflow
metadata:
  name: subflow
  namespace: default
spec:
  manifest:
    steps:
      - step: What's the current number
      - step: Mod that by 3 and then pick apple, orange, or banana, treating that list as an array and pick the index according to the modulus.
    output: Print the chose fruit

---
apiVersion: otto.gptscript.ai/v1
kind: WorkflowExecution
metadata:
  name: test
  namespace: default
spec:
  workflowName: wf
